"""从原始 Unicode/GBK 配对表生成双向直接查表数据，不依赖系统编码器。"""

import argparse
from pathlib import Path
import re


SOURCE = Path(__file__).with_name("cc936.c")
MAPPING = Path(__file__).with_name("cc936_mapping.inc")
PAIR_TABLE = re.compile(r"const WCHAR uni2oem\[\] = \{(.*?)\};", re.S)
UNICODE_TABLE = re.compile(
    r"/\* BEGIN GENERATED UNICODE TABLE \*/.*?/\* END GENERATED UNICODE TABLE \*/", re.S
)
OEM_TABLE = re.compile(
    r"/\* BEGIN GENERATED OEM TABLE \*/.*?/\* END GENERATED OEM TABLE \*/", re.S
)


def read_mapping(source):
    """保留原始映射和终止项，生成前检查排序、范围及反向映射唯一性。"""
    match = PAIR_TABLE.search(source)
    if not match:
        raise ValueError("找不到原始 uni2oem 配对表")
    values = re.sub(r"/\*.*?\*/", "", match.group(1), flags=re.S)
    numbers = [int(value.strip(), 0) for value in values.split(",") if value.strip()]
    if len(numbers) % 2 or numbers[-2:] != [0, 0]:
        raise ValueError("配对表必须包含完整映射及末尾 0, 0")
    pairs = list(zip(numbers[0:-2:2], numbers[1:-2:2]))
    if any(not (0x80 <= key <= 65535 and 0 < value <= 65535) for key, value in pairs):
        raise ValueError("映射超出扩展字符范围，ASCII 由转换函数直接处理")
    if any(pairs[i-1][0] >= pairs[i][0] for i in range(1, len(pairs))):
        raise ValueError("Unicode 配对表必须严格递增")
    if len({oem for _, oem in pairs}) != len(pairs):
        raise ValueError("反向映射存在重复 GBK 值")
    return pairs


def generate_unicode_table(pairs, newline):
    """高字节索引非空页；缺省索引为零，共用一页全零结果。"""
    page_index = [0] * 256
    pages = [[0] * 256]
    page_high_bytes = [None]
    for unicode, oem in pairs:
        high = unicode >> 8
        if page_index[high] == 0:
            page_index[high] = len(pages)
            pages.append([0] * 256)
            page_high_bytes.append(high)
        pages[page_index[high]][unicode & 0xff] = oem
    if len(pages) > 256:
        raise ValueError("页号超出 BYTE 范围")
    lines = [
        "/* BEGIN GENERATED UNICODE TABLE */",
        "/* Generated by generate_cc936_table.py from cc936_mapping.inc; do not edit. */",
        "/* High byte selects a 256-code-point page. Index zero selects the shared",
        " * empty page, so every character needs exactly two table reads. */",
        "static const BYTE unicode_page_index[256] = {",
    ]
    for start in range(0, 256, 16):
        lines.append("\t" + ", ".join("%3u" % value for value in page_index[start:start+16]) + ",")
    lines.extend(["};", "", "static const WCHAR unicode_pages[%u][256] = {" % len(pages)])
    for high, page in zip(page_high_bytes, pages):
        label = "Shared empty page" if high is None else "U+%02X00..U+%02XFF" % (high, high)
        lines.append("\t{ /* %s */" % label)
        for start in range(0, 256, 16):
            lines.append("\t\t" + ", ".join("0x%04X" % value for value in page[start:start+16]) + ",")
        lines.append("\t},")
    lines.extend(["};", "/* END GENERATED UNICODE TABLE */"])
    return newline.join(lines), 256 + len(pages) * 256 * 2


def generate_oem_table(pairs, newline):
    dense = [0] * (126 * 190)
    single = []
    for unicode, oem in pairs:
        if oem < 256:
            single.append((unicode, oem))
            continue
        lead, trail = oem >> 8, oem & 255
        if not (0x81 <= lead <= 0xfe and 0x40 <= trail <= 0xfe and trail != 0x7f):
            raise ValueError("配对表出现 GBK 双字节范围之外的编码")
        column = trail - 0x40 - (trail > 0x7f)
        dense[(lead - 0x81) * 190 + column] = unicode
    if single != [(0x20ac, 0x80)]:
        raise ValueError("单字节扩展必须保持 CP936 的 0x80 欧元符号")
    lines = [
        "/* BEGIN GENERATED OEM TABLE */",
        "/* Generated by generate_cc936_table.py from cc936_mapping.inc; do not edit. */",
        "/* Lead bytes 0x81..0xFE, 190 trail bytes 0x40..0xFE excluding 0x7F.",
        " * Undefined pairs contain zero. The single-byte Euro is handled below. */",
        "static const WCHAR oem2uni[126 * 190] = {",
    ]
    for row in range(126):
        lines.append("\t/* Lead byte 0x%02X */" % (row + 0x81))
        for column in range(0, 190, 10):
            start = row * 190 + column
            lines.append("\t" + ", ".join("0x%04X" % value for value in dense[start:start+10]) + ",")
    lines.extend(["};", "/* END GENERATED OEM TABLE */"])
    return newline.join(lines)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="只验证两张表是否与原始配对表一致")
    args = parser.parse_args()
    source = SOURCE.read_bytes().decode("ascii")
    pairs = read_mapping(MAPPING.read_text(encoding="ascii"))
    newline = "\r\n" if "\r\n" in source else "\n"
    unicode_table, unicode_bytes = generate_unicode_table(pairs, newline)
    oem_table = generate_oem_table(pairs, newline)
    for pattern, generated in ((UNICODE_TABLE, unicode_table), (OEM_TABLE, oem_table)):
        match = pattern.search(source)
        if not match:
            raise SystemExit("缺少查找表的生成标记")
        if args.check:
            if match.group(0) != generated:
                raise SystemExit("cc936 查找表与配对表不一致，请重新生成")
        else:
            source = source[:match.start()] + generated + source[match.end():]
    if not args.check:
        SOURCE.write_bytes(source.encode("ascii"))
    print("CP936 direct tables: %u mappings %s; Unicode %u + OEM 47880 bytes, no RAM."
          % (len(pairs), "verified" if args.check else "generated", unicode_bytes))


if __name__ == "__main__":
    main()
